import type { Metadata } from "next";
import "./globals.css";

import { Providers } from "./provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <title>Fotos AI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="">
        <div className="min-h-full">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
