import type { Metadata } from "next";
import { Onborda, OnbordaProvider } from "onborda";
// import localFont from "next/font/local";
import "./globals.css";
import { Tour } from "onborda/dist/types";
import CustomCard from "./components/CustomCard";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const tour1: Tour[] = [
    {
      tour: "tour1",
      steps: [
        {
          icon: <>👋</>,
          title: "Tour 1, Step 1",
          content: <>First tour, first step</>,
          selector: "#onborda-step1",
          side: "top",
          showControls: true,
          pointerPadding: 10,
          pointerRadius: 10,
          // nextRoute: "/foo",
          // prevRoute: "/bar",
        },
        {
          icon: <>👋</>,
          title: "Tour 1, Step 2",
          content: <>First tour, second step</>,
          selector: "#onborda-step2",
          side: "top",
          showControls: true,
          pointerPadding: 10,
          pointerRadius: 10,
          // nextRoute: "/foo",
          // prevRoute: "/bar",
        },
      ],
    },
  ];

  return (
    <html lang="en">
      <head>
        <title>Fotos AI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <div className="min-h-full">
        <OnbordaProvider>
          <Onborda
            showOnborda={true}
            steps={tour1}
            shadowOpacity="0.8"
            cardComponent={CustomCard}
            cardTransition={{ duration: 0.5, type: "tween" }}
          >
            <body className="">{children}</body>
          </Onborda>
        </OnbordaProvider>
      </div>
    </html>
  );
}
